apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-app
  namespace: argocd
spec:
  destination:
    namespace: bgd
    server: https://api.xnkpeyx0.canadacentral.aroapp.io:6443
  project: default
  source:
    path: apps/bgd/overlays/bgd
    repoURL: https://github.com/ashish6913/openshift-gitops-examples.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
